name: Flask App CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Flask App
        run: |
          # Add any additional build steps if needed
          python3 app.py

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies for GitHub Pages Deployment
        run: |
          npm install -g gh-pages

      - name: Deploy to GitHub Pages
        run: |
          gh-pages -d path/to/static/assets -b gh-pages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
